#include <iostream>
#include <stdio.h>
using namespace std;
int main ()
{
    long long int n,t,a,b,c,d,e,f;
    cin>>t;
    while(t--)
    {
        cin>>n;
        a=1;
        b=0;
        c=0;
        while(1)
        {
            ++b;
            if(b<10)
            {
                ++c;
                d=b;
                if(c==n)
                {
                    cout<<b<<endl;
                    break;
                }
            }
            else if(b<100)
            {
                f=b;
                c+=2;
                e=c;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
            }
            else if(b<1000)
            {
                f=b;
                c+=3;
                e=c;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
            }
            else if(b<10000)
            {
                f=b;
                c+=4;
                e=c;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
            }
            else if(b<100000)
            {
                f=b;
                c+=5;
                e=c;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
            }
            else if(b<1000000)
            {
                f=b;
                c+=6;
                e=c;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                 e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
            }
            else if(b<10000000)
            {
                f=b;
                c+=7;
                e=c;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                 e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
            }
            else if(b<100000000)
            {
                f=b;
                c+=8;
                e=c;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                 e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
            }
             else if(b<1000000000)
            {
                f=b;
                c+=9;
                e=c;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                 e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                 e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
            }
             else
            {
                f=b;
                c+=10;
                e=c;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                 e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
                 e-=1;
                d=f%10;
                f/=10;
                if(e==n)
                {
                    cout<<d<<endl;
                    break;
                }
            }
            if(a==b)
            {
                ++a;
                b=0;
            }
        }
    }
    return 0;
}
