#include <iostream>
#include <stdio.h>
#include <string.h>
using namespace std;
char arr[35][35][35];
int len,flag,flag2;
void bfs(int a,int b,int c,int i,int j,int k)
{
    arr[i][j][k]='#';
    int flag1=0,children1[43000][3],children2[43000][3],m=1,n=0,y,d,e,f;
    flag2=0;
    children1[0][0]=i;
    children1[0][1]=j;
    children1[0][2]=k;
    while(1)
    {
        flag2=0;
        if(flag1==0)
        {
            n=0;
            for(y=0; y<m; y++)
            {
                i=children1[y][0];
                j=children1[y][1];
                k=children1[y][2];
                d=i+1;
                e=j;
                f=k;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children2[n][0]=d;
                        children2[n][1]=e;
                        children2[n][2]=f;
                        n++;
                    }
                }
                d=i-1;
                e=j;
                f=k;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children2[n][0]=d;
                        children2[n][1]=e;
                        children2[n][2]=f;
                        n++;
                    }
                }
                d=i;
                e=j+1;
                f=k;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children2[n][0]=d;
                        children2[n][1]=e;
                        children2[n][2]=f;
                        n++;
                    }
                }
                d=i;
                e=j-1;
                f=k;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children2[n][0]=d;
                        children2[n][1]=e;
                        children2[n][2]=f;
                        n++;
                    }
                }
                d=i;
                e=j;
                f=k+1;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children2[n][0]=d;
                        children2[n][1]=e;
                        children2[n][2]=f;
                        n++;
                    }
                }
                d=i;
                e=j;
                f=k-1;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children2[n][0]=d;
                        children2[n][1]=e;
                        children2[n][2]=f;
                        n++;
                    }
                }
            }
            flag1=1;
        }
        else
        {
            m=0;
            for(y=0; y<n; y++)
            {
                i=children2[y][0];
                j=children2[y][1];
                k=children2[y][2];
                d=i+1;
                e=j;
                f=k;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children1[m][0]=d;
                        children1[m][1]=e;
                        children1[m][2]=f;
                        m++;
                    }
                }
                d=i-1;
                e=j;
                f=k;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children1[m][0]=d;
                        children1[m][1]=e;
                        children1[m][2]=f;
                        m++;
                    }
                }
                d=i;
                e=j+1;
                f=k;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children1[m][0]=d;
                        children1[m][1]=e;
                        children1[m][2]=f;
                        m++;
                    }
                }
                d=i;
                e=j-1;
                f=k;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children1[m][0]=d;
                        children1[m][1]=e;
                        children1[m][2]=f;
                        m++;
                    }
                }
                d=i;
                e=j;
                f=k+1;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children1[m][0]=d;
                        children1[m][1]=e;
                        children1[m][2]=f;
                        m++;
                    }
                }
                d=i;
                e=j;
                f=k-1;
                if(d>=0&&d<a&&e>=0&&e<b&&f>=0&&f<c)
                {
                    if(arr[d][e][f]!='#')
                    {
                        flag2=1;
                        if(arr[d][e][f]=='E')
                        {
                            flag=1;
                            break;
                        }
                        arr[d][e][f]='#';
                        children1[m][0]=d;
                        children1[m][1]=e;
                        children1[m][2]=f;
                        m++;
                    }
                }
            }
            flag1=0;
        }
        len++;
        if(flag2==0)
            break;
        if(flag==1)
            break;
    }
    return;
}
int main ()
{
    int a,b,c,i,j,k;
    char z;
    while((scanf("%d %d %d",&a,&b,&c))==3)
    {
        scanf("%c",&z);
        if(a==0&&b==0&&c==0)
            break;
        len=flag=0;
        for(i=0; i<a; i++)
          {
              for(j=0; j<b+1; j++)
                gets(arr[i][j]);
          }
        for(i=0; i<a; i++)
            for(j=0; j<b; j++)
                for(k=0; k<c; k++)
                {
                    if(arr[i][j][k]=='S')
                        bfs(a,b,c,i,j,k);
                    break;
                }
                if(flag==0)
                cout<<"Trapped!"<<endl;
                else
                printf("Escaped in %d minute(s).\n",len);
    }
    return 0;
}
